### ISSUE TITLE
Changing the vision radius doesnt update the displayd areas and outlines

### ISSUE THREAD

**Issue by bernikr** [cubedhuang/boids#1]
When I check "show vision areas" or "show vision outlines" and then change the vision radius the displayed circles are not updated. Only when I uncheck or check one of the two options it is updated for both again.

**Comment by cubedhuang** [comment]
ive known this issue for like 2 years im lazy

**Comment by cubedhuang** [comment]
you're welcome to try and navigate my spaghettifest of a project to fix it yourself if you really wanna
