### ISSUE TITLE
Switch to MIT License?

### ISSUE THREAD

**Issue by camden** [cubedhuang/boids#3]
Hi, 

First of all, this website is so cool. I've had a lot of fun playing around with different settings.

I'm interested in building off of it for fun + a personal project, but I'm dissuaded by the GPLv3 license. I would feel more comfortable working with it if it had an MIT license. Would you be open to changing the license to MIT?

I intend to use this project as a foundation for generative art. I won't be using this for NFTs tho. I'm interested in exploring adding RNG to the site and more customization. Maybe some more critters. 

I'd be happy to open a PR to change the license. 

I'm curious to hear your thoughts! 

Thanks,
Cam

**Comment by cubedhuang** [comment]
Sounds fine to me! I'd love to see your project come out of this.

**Comment by camden** [comment]
Thank you! I'll let you know how my project goes, and I'll def credit you. :) Happy new year!
